baseURL: https://blog.zhiheng.io/
languageCode: en-us
title: "Zhiheng's Blog"

theme: "PaperMod"

googleAnalytics: UA-77295418-1

params:
  customCSS:
  - style.css

  # Params of PaperMod theme
  ShowPostNavLinks: true

markup:
  goldmark:
    renderer:
      unsafe: true